# Space saving settings.
QMK_SETTINGS = no
LTO_ENABLE = yes
COMBO_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = no
AUTO_SHIFT_ENABLE = yes
